project/Clase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name = 'Clase'

urlpatterns = [
    path("", views.home, name="home"),
    #path("ejerciciocategoria/create/", views.ejerciciocategoria_create, name="ejerciciocategoria_create"),
    path("ejerciciocategoria/create/", views.EjercicioCategoriaCreate.as_view(), name="ejerciciocategoria_create"),
    #path("ejerciciocategoria/list/", views.ejerciciocategoria_list, name="ejerciciocategoria_list"),
    path("ejerciciocategoria/list/", views.EjercicioCategoriaList.as_view(), name="ejerciciocategoria_list"),
    path("ejerciciocategoria/detail/<int:pk>/", views.EjercicioCategoriaDetail.as_view(), name="ejerciciocategoria_detail"),
    path("ejerciciocategoria/update/<int:pk>/", views.EjercicioCategoriaUpdate.as_view(), name="ejerciciocategoria_update"),
    path("ejerciciocategoria/delete/<int:pk>/", views.EjercicioCategoriaDelete.as_view(), name="ejerciciocategoria_delete"),
    #path("tema/create/", views.tema_create, name="tema_create"),
    #path("solucion/create/", views.solucion_create, name="solucion_create"),
]

urlpatterns += [
    path("solucion/create/", views.SolucionCreate.as_view(), name="solucion_create"),
    path("solucion/list/", views.SolucionList.as_view(), name="solucion_list"),
    path("solucion/detail/<int:pk>/", views.SolucionDetail.as_view(), name="solucion_detail"),
    path("solucion/update/<int:pk>/", views.SolucionUpdate.as_view(), name="solucion_update"),
    path("solucion/delete/<int:pk>/", views.SolucionDelete.as_view(), name="solucion_delete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("Clase/", include("Clase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
app_name = 'core'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path('register/', views.register, name="register"),
    path('about/', views.about, name="about"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/Clase/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class Ciclo(models.Model):
    nombre = models.CharField(max_length=100, unique=True, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Profesor(models.Model):
    nombre = models.CharField(max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Curso(models.Model):
    nombre = models.CharField(max_length=100, unique=True, blank=True, null=True)
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE, related_name='cursos')
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL, null=True, related_name='cursos')
    
    def __str__(self):
        return self.nombre

class Tema(models.Model):
    nombre = models.CharField(max_length=100, blank=True, null=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, related_name='temas')
    
    def __str__(self):
        return self.nombre

class EjercicioCategoria(models.Model):
    enunciado = models.TextField(blank=True, null=True)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE, related_name='ejercicios')
    fecha_creacion = models.DateField(default=datetime.now, blank=True, null=True, editable=False)
    imagen = models.ImageField(upload_to='ejercicios/', blank=True, null=True)
    
    def __str__(self):
        return f"Ejercicio numero {self.id}"

class Solucion(models.Model):
    solucion = models.TextField(blank=True, null=True)
    ejercicio_id = models.ForeignKey(EjercicioCategoria, on_delete=models.CASCADE, related_name='soluciones')
    fecha_creacion = models.DateField(default=datetime.now, blank=True, null=True, editable=False)
    imagen = models.ImageField(upload_to='soluciones/', blank=True, null=True)
    
    def __str__(self):
        return f"Solución del ejercicio número {self.ejercicio_id.id}"

class Estudiante(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='estudiante')
    avatar = models.ImageField(upload_to='avatares/', blank=True, null=True)

    def __str__(self):
        return self.usuario.username

project/Clase/forms.py
from django import forms
from . import models

    #enunciado = models.TextField(blank=True, null=True)
    #tema = models.ForeignKey(Tema, on_delete=models.CASCADE, related_name='ejercicios')
    
    #enunciado = forms.CharField()
    #tema = forms.CharField()

class EjercicioCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.EjercicioCategoria
        fields = ['enunciado', 'tema', 'imagen']  # Solo los campos que se mostrarán en el formulario
        widgets = {
            "enunciado": forms.Textarea(attrs={"class": "form-control", "placeholder": "Enunciado"}),
            "tema": forms.Select(attrs={"class": "form-control"}),
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control-file"})  # Para la carga de imágenes
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['enunciado'].label = "Enunciado"  # Cambiar la etiqueta del campo enunciado
        self.fields['tema'].label = "Tema"  # Cambiar la etiqueta del campo tema
        self.fields['imagen'].label = "Imagen"

"""class TemaForm(forms.ModelForm):
    class Meta:
        model = models.Tema
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre"}),
            "curso": forms.Select(attrs={"class": "form-control"}),
        }"""

class SolucionForm(forms.ModelForm):
    class Meta:
        model = models.Solucion
        fields = ['solucion', 'ejercicio_id', 'imagen']  # Asegúrate de incluir el campo 'ejercicio_id'
        widgets = {
            "solucion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Solución"}),
            "ejercicio_id": forms.Select(attrs={"class": "form-control"}),  # Asegúrate de incluir un campo para seleccionar el ejercicio
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control-file"})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['solucion'].label = "Solución"
        self.fields['ejercicio_id'].label = "Ejercicio"  # Cambia la etiqueta del campo a "Ejercicio"
        self.fields['imagen'].label = "Imagen"

project/Clase/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

def home(request):
    return render(request, 'Clase/index.html')

"""def ejerciciocategoria_list(request):
    consulta = request.GET.get("consulta", None)
    if consulta:
        cursos = models.Curso.objects.filter(nombre__icontains=consulta)
    else:
        cursos = models.Curso.objects.all()
    context = {"cursos": cursos}
    return render(request, 'Clase/ejerciciocategoria_list.html', context)"""

class EjercicioCategoriaCreate(LoginRequiredMixin, CreateView):
    model = models.EjercicioCategoria
    form_class = forms.EjercicioCategoriaForm
    success_url = reverse_lazy('Clase:home')

class EjercicioCategoriaUpdate(LoginRequiredMixin, UpdateView):
    model = models.EjercicioCategoria
    form_class = forms.EjercicioCategoriaForm
    success_url = reverse_lazy('Clase:ejerciciocategoria_list')

class EjercicioCategoriaDelete(LoginRequiredMixin, DeleteView):
    model = models.EjercicioCategoria
    success_url = reverse_lazy('Clase:ejerciciocategoria_list')

"""class EjercicioCategoriaList(ListView):
    model = models.EjercicioCategoria
    context_object_name = 'ejercicios'
    template_name = 'Clase/ejerciciocategoria_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cursos'] = models.Curso.objects.all()
        return context

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.EjercicioCategoria.objects.filter(enunciado__icontains=consulta)
        else:
            object_list = models.EjercicioCategoria.objects.all()
        return object_list"""

class EjercicioCategoriaList(LoginRequiredMixin, ListView):
    model = models.Curso
    context_object_name = 'cursos'
    template_name = 'Clase/ejerciciocategoria_list.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        consulta = self.request.GET.get("consulta")
        if consulta:
            queryset = queryset.filter(nombre__icontains=consulta)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['consulta'] = self.request.GET.get("consulta", "")
        return context

class EjercicioCategoriaDetail(LoginRequiredMixin, DetailView):
    model = models.EjercicioCategoria
    context_object_name = 'ejercicio'
    template_name = 'Clase/ejerciciocategoria_detail.html'

"""def ejerciciocategoria_create(request):
    if request.method == 'POST':
        form = forms.EjercicioCategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Clase:home')
    else:  # request.method == 'GET':
        form = forms.EjercicioCategoriaForm()
    return render(request, 'Clase/ejerciciocategoria_create.html', context={'form': form})"""

def tema_create(request):
    if request.method == 'POST':
        form = forms.TemaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Clase:home')
    else:  # request.method == 'GET':
        form = forms.TemaForm()
    return render(request, 'Clase/tema_create.html', context={'form': form})

def solucion_create(request):
    if request.method == 'POST':
        form = forms.SolucionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Clase:home')
    else:  # request.method == 'GET':
        form = forms.SolucionForm()
    return render(request, 'Clase/solucion_create.html', context={'form': form})

#**************************************************************

class SolucionCreate(LoginRequiredMixin, CreateView):
    model = models.Solucion
    form_class = forms.SolucionForm
    success_url = reverse_lazy('Clase:home')

    def form_valid(self, form):
        form.instance.ejercicio_id = models.EjercicioCategoria.objects.get(pk=self.request.POST.get('ejercicio_id'))  # Asigna el ejercicio seleccionado en el formulario
        return super().form_valid(form)

class SolucionUpdate(LoginRequiredMixin, UpdateView):
    model = models.Solucion
    form_class = forms.SolucionForm
    success_url = reverse_lazy('Clase:solucion_list')

class SolucionDelete(LoginRequiredMixin, DeleteView):
    model = models.Solucion
    success_url = reverse_lazy('Clase:solucion_list')

class SolucionList(LoginRequiredMixin, ListView):
    model = models.Solucion
    context_object_name = 'soluciones'
    template_name = 'Clase/solucion_list.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        consulta = self.request.GET.get("consulta")
        if consulta:
            queryset = queryset.filter(
                Q(solucion__icontains=consulta) | 
                Q(ejercicio_id__tema__curso__nombre__icontains=consulta)
            )
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['consulta'] = self.request.GET.get("consulta", "")
        return context

class SolucionDetail(LoginRequiredMixin, DetailView):
    model = models.Solucion
    context_object_name = 'solucion'
    template_name = 'Clase/solucion_detail.html'

project/Clase/templates/Clase/ejerciciocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Ejercicios: Borrar una categoría de ejercicios
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h1 class="card-title mb-1">
                        Categoría de ejercicios: BORRAR
                    </h1>
                </div>
            </div>
            <div class="mt-3 text-center"> <!-- Espacio entre la tarjeta y el contenido, centrado -->
                
                <p class="fs-5 fst-italic">¿Confirma eliminar el ejercicio: "{{ object.id }}"?</p>
                <!-- Contenido -->
                {#<p>Contenido</p>#}
                
                <form action="" method="post">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-danger">Confirmar</button>
                </form>
                
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center mt-4">
    <a href="{% url 'Clase:home' %}" class="btn btn-secondary btn-lg">Volver a Clase</a>
</div>
{% endblock content %}

project/Clase/templates/Clase/ejerciciocategoria_create.html
{% extends 'core/base.html' %}

{% block title %}
    Crear ejercicios
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h1 class="card-title mb-1">
                        Categoría de ejercicios: creación
                    </h1>
                </div>
            </div>
            <div class="mt-3 text-center"> <!-- Espacio entre la tarjeta y el contenido, centrado -->
                
                <!-- Contenido -->
                {#<p>Contenido</p>#}
                
                <form action="" method="post">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-secondary">Guardar</button>
                </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

project/Clase/templates/Clase/ejerciciocategoria_detail.html
{% extends 'core/base.html' %}

{% block title %}
    Ejercicios: Detalle de ejercicio
{% endblock title %}

{% block content %}
    {% include 'core/components/masthead.html' with titulo="Ciclo 3" texto="2do fisiaño" boton="Go" %}
    <div class="container py-lg-4">
        <form action="{% url 'Clase:ejerciciocategoria_list' %}" method="get" class="mb-4">
            <input type="text" name="consulta" placeholder="Buscar..." class="form-control">
        </form>
        {% if ejercicio %}
            <ul>
                <li>
                    <strong>Tema:</strong> {{ ejercicio.tema.nombre }}<br>
                    <strong>Enunciado:</strong> {{ ejercicio.enunciado }}<br>
                    {% if ejercicio.imagen %}
                        <img src="{{ ejercicio.imagen.url }}" alt="Imagen de ejercicio">
                    {% endif %}
                </li>
            </ul>
        {% else %}
            <p>No se encontró el ejercicio.</p>
        {% endif %}
    </div>
    <div class="d-flex justify-content-center mt-4">
        <a href="{% url 'Clase:ejerciciocategoria_list' %}" class="btn btn-secondary btn-lg">Volver</a>
    </div>
{% endblock content %}

project/Clase/templates/Clase/ejerciciocategoria_form.html
{% extends 'core/base.html' %}

{% block title %}
    Ejercicios: crear categoría de ejercicios
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h1 class="card-title mb-1">
                        Categoría de ejercicios: creación
                    </h1>
                </div>
            </div>
            <div class="mt-3 text-center"> <!-- Espacio entre la tarjeta y el contenido, centrado -->
                
                <!-- Contenido -->
                {#<p>Contenido</p>#}
                
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error:</strong>
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <button type="submit" class="btn btn-secondary">Guardar</button>
                </form>
                
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center mt-4">
    <a href="{% url 'Clase:home' %}" class="btn btn-secondary btn-lg">Volver a Clase</a>
</div>
{% endblock content %}

project/Clase/templates/Clase/ejerciciocategoria_list.html
{% extends 'core/base.html' %}

{% block title %}
    Ejercicios: Lista de categoría de ejercicios
{% endblock title %}

{% block content %}
    {% include 'core/components/masthead.html' with titulo="Ciclo 3" texto="2do fisiaño" boton="Go" %}
    <div class="container py-lg-4">
        <form action="{% url 'Clase:ejerciciocategoria_list' %}" method="get" class="mb-4">
            <input type="text" name="consulta" placeholder="Buscar por curso..." class="form-control" value="{{ consulta }}">
        </form>
        {% if cursos %}
            {% for curso in cursos %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h3 class="card-title">{{ curso.nombre }}</h3>
                        <p>Profesor: {{ curso.profesor }}</p>
                        <h4>Temas</h4>
                        <ul>
                            {% for tema in curso.temas.all %}
                                <li>
                                    {{ tema.nombre }}
                                    <ul>
                                        {% for ejercicio in tema.ejercicios.all %}
                                            <li>
                                                <strong>Ejercicio:</strong> {{ ejercicio.enunciado|truncatechars:100 }}
                                                {% if ejercicio.imagen %}
                                                    <img src="{{ ejercicio.imagen.url }}" alt="Imagen de ejercicio">
                                                {% endif %}
                                                <a href="{% url 'Clase:ejerciciocategoria_detail' ejercicio.id %}">Detalle</a>
                                                <a href="{% url 'Clase:ejerciciocategoria_update' ejercicio.id %}">Cambiar</a>
                                                <a href="{% url 'Clase:ejerciciocategoria_delete' ejercicio.id %}">Borrar</a>
                                            </li>
                                            <li><strong>Solución:</strong> {{ ejercicio.solucion.solucion|truncatechars:100 }}</li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No se encontraron cursos.</p>
        {% endif %}
    </div>
    <div class="d-flex justify-content-center mt-4">
        <a href="{% url 'Clase:home' %}" class="btn btn-secondary btn-lg">Volver a Clase</a>
    </div>
{% endblock content %}

project/Clase/templates/Clase/ejerciciocategoria_update.html
{% extends 'core/base.html' %}

{% block title %}
    Ejercicios: Cambiar categoría de ejercicios
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h1 class="card-title mb-1">
                        Categoría de ejercicios: creación
                    </h1>
                </div>
            </div>
            <div class="mt-3 text-center"> <!-- Espacio entre la tarjeta y el contenido, centrado -->
                
                <!-- Contenido -->
                {#<p>Contenido</p>#}
                
                <form action="" method="post">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-secondary">Guardar</button>
                </form>
                
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center mt-4">
    <a href="{% url 'Clase:ejerciciocategoria_list' %}" class="btn btn-secondary btn-lg">Volver</a>
</div>
{% endblock content %}

project/Clase/templates/Clase/index.html
{% extends 'core/base.html' %}

{% block title %}
    CICLOS
{% endblock title %}

{% block content %}
    {% include 'core/components/masthead.html' with titulo="Ciclo 3" texto="2do fisiaño" boton="Go"%}
    <div class="d-flex justify-content-center align-items-center vh-100">
        
        <div class="container">
            <!-- Sección Ejercicios -->
            <div class="btn-group d-flex flex-column mb-4" role="group">
                <h3>Ejercicios</h3>
                <a href="{% url 'Clase:ejerciciocategoria_create' %}" class="btn btn-primary flex-fill mb-3">Sube tus ejercicios</a>
                <a href="{% url 'Clase:ejerciciocategoria_list' %}" class="btn btn-primary flex-fill mb-3">Listar ejercicios</a>
            </div>
            <!-- Sección Soluciones -->
            <div class="btn-group d-flex flex-column mb-4" role="group">
                <h3>Soluciones</h3>
                <a href="{% url 'Clase:solucion_create' %}" class="btn btn-primary flex-fill mb-3">Sube tus soluciones</a>
                <a href="{% url 'Clase:solucion_list' %}" class="btn btn-primary flex-fill mb-3">Listar soluciones</a>
            </div>
            <!-- Botón Volver a Inicio -->
            <div class="d-flex justify-content-center mt-4">
                <a href="{% url 'core:home' %}" class="btn btn-secondary btn-lg">Volver a inicio</a>
            </div>
        </div>
            {% for ciclo in ciclos %}
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <div class="card">
                            <div class="card-body text-center">
                                <h2 class="card-title">{{ ciclo.nombre }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
                {% for curso in ciclo.cursos.all %}
                    <div class="row">
                        <div class="col-md-12">
                            <h3>{{ curso.nombre }}</h3>
                            <p>Profesor: {{ curso.profesor }}</p>
                            <h4>Temas</h4>
                            <ul>
                                {% for tema in curso.temas.all|dictsort:"nombre" %}
                                    <li>{{ tema.nombre }}</li>
                                    <ul>
                                        {% for ejercicio in tema.ejercicios.all %}
                                            <li>{{ ejercicio }}</li>
                                            <li>{{ ejercicio.solucion }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

project/Clase/templates/Clase/solucion_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
    Solución: Borrar una solución
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h1 class="card-title mb-1">
                        Solución: BORRAR
                    </h1>
                </div>
            </div>
            <div class="mt-3 text-center">
                
                <p class="fs-5 fst-italic">¿Confirma eliminar la solución: "{{ object.id }}"?</p>
                
                <form action="" method="post">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-danger">Confirmar</button>
                </form>
                
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center mt-4">
    <a href="{% url 'Clase:home' %}" class="btn btn-secondary btn-lg">Volver a Clase</a>
</div>
{% endblock content %}

project/Clase/templates/Clase/solucion_create.html
{% extends 'core/base.html' %}

{% block title %}
    Crear soluciones
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h1 class="card-title mb-1">
                        Categoría de Soluciones: creación
                    </h1>
                </div>
            </div>
            <div class="mt-3 text-center"> <!-- Espacio entre la tarjeta y el contenido, centrado -->
                
                <!-- Contenido -->
                {#<p>Contenido</p>#}
                
                <form action="" method="post">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-primary ">Guardar</button>
                </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

project/Clase/templates/Clase/solucion_detail.html
{% extends 'core/base.html' %}

{% block title %}
    Solución: Detalle de solución
{% endblock title %}

{% block content %}
    {% include 'core/components/masthead.html' with titulo="Ciclo 3" texto="2do fisiaño" boton="Go" %}
    <div class="container py-lg-4">
        <form action="{% url 'Clase:solucion_list' %}" method="get" class="mb-4">
            <input type="text" name="consulta" placeholder="Buscar..." class="form-control">
        </form>
        {% if solucion %}
            <ul>
                <li>
                    <strong>Tema:</strong> {{ solucion.ejercicio_id.tema.nombre }}<br>
                    {% if solucion.imagen %}
                        <img src="{{ solucion.imagen.url }}" alt="Imagen de solución">
                    {% endif %}
                    <strong>Solución:</strong> {{ solucion.solucion }}
                </li>
            </ul>
        {% else %}
            <p>No se encontró la solución.</p>
        {% endif %}
    </div>
    <div class="d-flex justify-content-center mt-4">
        <a href="{% url 'Clase:solucion_list' %}" class="btn btn-secondary btn-lg">Volver</a>
    </div>
{% endblock content %}

project/Clase/templates/Clase/solucion_list.html
{% extends 'core/base.html' %}

{% block title %}
    Solución: Lista de soluciones
{% endblock title %}

{% block content %}
    {% include 'core/components/masthead.html' with titulo="Ciclo 3" texto="2do fisiaño" boton="Go" %}
    <div class="container py-lg-4">
        <form action="{% url 'Clase:solucion_list' %}" method="get" class="mb-4">
            <input type="text" name="consulta" placeholder="Buscar por curso..." class="form-control" value="{{ consulta }}">
        </form>
        {% if soluciones %}
            <h2>{{ soluciones.0.ejercicio_id.tema.curso.nombre }}</h2> <!-- Se toma el nombre del curso del primer ejercicio/solución -->
            {% for solucion in soluciones %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h3 class="card-title">Ejercicio: {{ solucion.ejercicio_id.enunciado|truncatechars:100 }}</h3>
                        {% if solucion.ejercicio_id.imagen %}
                            <img src="{{ solucion.ejercicio_id.imagen.url }}" alt="Imagen de ejercicio">
                        {% endif %}
                        <h4 class="mt-3">Solución:</h4>
                        {% if solucion.imagen %}
                            <img src="{{ solucion.imagen.url }}" alt="Solución" style="max-width: 200px; max-height: 200px;">
                        {% else %}
                            {{ solucion.solucion|truncatechars:100 }}
                        {% endif %}
                        <a href="{% url 'Clase:solucion_detail' solucion.id %}">Detalle</a>
                        <a href="{% url 'Clase:solucion_update' solucion.id %}">Cambiar</a>
                        <a href="{% url 'Clase:solucion_delete' solucion.id %}">Borrar</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No se encontraron soluciones.</p>
        {% endif %}
    </div>
    <div class="d-flex justify-content-center mt-4">
        <a href="{% url 'Clase:home' %}" class="btn btn-secondary btn-lg">Volver a Clase</a>
    </div>
{% endblock content %}