project/Clase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name = 'Clase'

urlpatterns = [
    path("", views.home, name="home"),
    #path("ejerciciocategoria/create/", views.ejerciciocategoria_create, name="ejerciciocategoria_create"),
    path("ejerciciocategoria/create/", views.EjercicioCategoriaCreate.as_view(), name="ejerciciocategoria_create"),
    #path("ejerciciocategoria/list/", views.ejerciciocategoria_list, name="ejerciciocategoria_list"),
    path("ejerciciocategoria/list/", views.EjercicioCategoriaList.as_view(), name="ejerciciocategoria_list"),
    path("ejerciciocategoria/detail/<int:pk>/", views.EjercicioCategoriaDetail.as_view(), name="ejerciciocategoria_detail"),
    path("ejerciciocategoria/update/<int:pk>/", views.EjercicioCategoriaUpdate.as_view(), name="ejerciciocategoria_update"),
    path("ejerciciocategoria/delete/<int:pk>/", views.EjercicioCategoriaDelete.as_view(), name="ejerciciocategoria_delete"),
    #path("tema/create/", views.tema_create, name="tema_create"),
    #path("solucion/create/", views.solucion_create, name="solucion_create"),
]

urlpatterns += [
    path("solucion/create/", views.SolucionCreate.as_view(), name="solucion_create"),
    path("solucion/list/", views.SolucionList.as_view(), name="solucion_list"),
    path("solucion/detail/<int:pk>/", views.SolucionDetail.as_view(), name="solucion_detail"),
    path("solucion/update/<int:pk>/", views.SolucionUpdate.as_view(), name="solucion_update"),
    path("solucion/delete/<int:pk>/", views.SolucionDelete.as_view(), name="solucion_delete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("Clase/", include("Clase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
app_name = 'core'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path('register/', views.register, name="register"),
    path('about/', views.about, name="about"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'})
        }

project/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.http import HttpRequest, HttpResponse

#@login_required
def home(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'core/login.html'
    next_page = '/'

def register(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()
            return render(request, 'core/index.html', {'mensaje': "usuario creado"})
    else:
        form = CustomUserCreationForm()
    return render(request, 'core/register.html', {'form': form})

project/core/templates/core/components/card.html
<div class="col-md-12">
    <a href="{% url 'Clase:home' %}">
        <span class="fa-stack fa-4x">
            <i class="fas fa-circle fa-stack-2x text-primary"></i>
            <i class="fas fa-graduation-cap fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="my-3">{{titulo}}</h4>
    </a>
        <p class="text-muted">{{texto}}</p>
    </div>

project/core/templates/core/components/footer.html
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">Copyright &copy; Fisisitio hecho en Coderhouse</div>
            <div class="col-lg-4 my-3 my-lg-0">
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
            </div>
        </div>
    </div>
</footer>

project/core/templates/core/components/masthead.html
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">{{texto}}</div>
        <div class="masthead-heading text-uppercase">{{titulo}}</div>
        <a class="btn btn-primary btn-xl text-uppercase" href="#services">{{boton}}</a>
    </div>
</header>

project/core/templates/core/components/navbar.html
{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{% static 'core/assets/img/navbar-logofisi.png' %}" alt="..." /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="#services">Ciclos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#about">Tema</a></li>
                <li class="nav-item">
                    <a class="nav-link text-bg-info" href="#">
                        <img src="{% if user.estudiante.avatar %}{{ user.estudiante.avatar.url }}{% else %}{% static 'core/assets/img/default-avatar.png' %}{% endif %}" style="width: 30px; height: 30px;" />
                        {{ user.username }}
                    </a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'core:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">Logout</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:register' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>